In [1]:
import pandas as pd
import os
from os.path import dirname

root_path = dirname(os.getcwd())

pd.set_option("display.max_columns", None)
data_dir = root_path + "/data/datasets/original/"
data_dir_processed = root_path + "/data/datasets/processed/"
data_dir_graphs = root_path + "/data/datasets/graphs/"

print(root_path, data_dir, data_dir_processed, data_dir_graphs, sep="\n")

/home/sebdis/ProcessMining/HGNN/HGNN_NA
/home/sebdis/ProcessMining/HGNN/HGNN_NA/data/datasets/original/
/home/sebdis/ProcessMining/HGNN/HGNN_NA/data/datasets/processed/
/home/sebdis/ProcessMining/HGNN/HGNN_NA/data/datasets/graphs/

In [2]:
dataset = "BPI20_RequestForPayment"

In [3]:
import pm4py

log = pm4py.read_xes(f"datasets/original/{dataset}.xes.gz")
log = pm4py.convert_to_dataframe(log)
log.to_csv(f"datasets/original/{dataset}.csv")

/home/sebdis/ProcessMining/HGNN/hgnn_env/lib/python3.10/site-packages/pm4py/util/dt_parsing/parser.py:77: UserWarning: ISO8601 strings are not fully supported with strpfromiso for Python versions below 3.11
  warnings.warn(

parsing log, completed traces ::   0%|          | 0/6886 [00:00<?, ?it/s]

In [4]:
filename = data_dir + dataset + ".csv"
raw_data = pd.read_csv(filename, index_col=False)
raw_data = raw_data.drop(columns="Unnamed: 0")
raw_data.head()

,id,org:resource,concept:name,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,case:concept:name,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-01-09 09:17:18+00:00,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2017-01-09 09:18:00+00:00,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,2017-01-10 12:42:32+00:00,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-03-03 09:51:13+00:00,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,2017-03-03 09:51:42+00:00,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [5]:
tab_all = raw_data.rename(
    columns={"case:concept:name": "CaseID", "concept:name": "Activity"}
)
tab_all.head()

,id,org:resource,Activity,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-01-09 09:17:18+00:00,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2017-01-09 09:18:00+00:00,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,2017-01-10 12:42:32+00:00,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017-03-03 09:51:13+00:00,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,2017-03-03 09:51:42+00:00,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [8]:
tab_all["Activity"].unique()

array(['Request For Payment SUBMITTED by EMPLOYEE',
       'Request For Payment FINAL_APPROVED by SUPERVISOR',
       'Request For Payment REJECTED by MISSING',
       'Request For Payment APPROVED by PRE_APPROVER', 'Request Payment',
       'Payment Handled', 'Request For Payment REJECTED by SUPERVISOR',
       'Request For Payment REJECTED by EMPLOYEE',
       'Request For Payment APPROVED by SUPERVISOR',
       'Request For Payment FINAL_APPROVED by DIRECTOR',
       'Request For Payment REJECTED by PRE_APPROVER',
       'Request For Payment SAVED by EMPLOYEE',
       'Request For Payment REJECTED by ADMINISTRATION',
       'Request For Payment APPROVED by ADMINISTRATION',
       'Request For Payment APPROVED by BUDGET OWNER',
       'Request For Payment REJECTED by BUDGET OWNER',
       'Request For Payment FOR_APPROVAL by ADMINISTRATION',
       'Request For Payment FINAL_APPROVED by BUDGET OWNER',
       'Request For Payment FOR_APPROVAL by SUPERVISOR'], dtype=object)

In [10]:
tab_all["time:timestamp"] = [x.split(".")[0] for x in tab_all["time:timestamp"]]

tab_all["time:timestamp"] = tab_all["time:timestamp"].str.replace("-", "/")
tab_all["time:timestamp"] = tab_all["time:timestamp"].str.split("+", expand=True)[0]

tab_all.head()

,id,org:resource,Activity,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017/01/09 09:17:18,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,2017/01/09 09:18:00,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,2017/01/10 12:42:32,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,2017/03/03 09:51:13,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,2017/03/03 09:51:42,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [11]:
from utils import translate_time

tab_all['time:timestamp'] = tab_all['time:timestamp'].apply(translate_time)
tab_all.head()

,id,org:resource,Activity,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,1.483950e+09,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,1.483950e+09,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,1.484049e+09,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,1.488531e+09,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,1.488531e+09,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [12]:
tab_all.columns

Index(['id', 'org:resource', 'Activity', 'time:timestamp', 'org:role',
       'case:Rfp_id', 'case:Project', 'case:Task', 'CaseID',
       'case:OrganizationalEntity', 'case:Cost Type', 'case:RequestedAmount',
       'case:Activity', 'case:RfpNumber'],
      dtype='object')

In [43]:
categorical_columns = ['org:resource', 'Activity', 'org:role',
      'case:Project', 'case:Task', 'CaseID',
       'case:OrganizationalEntity', 'case:Cost Type',
       'case:Activity', 'case:RfpNumber']
real_value_columns = ["time:timestamp", "case:RequestedAmount"]

In [78]:
tab_all = tab_all.fillna({key: "NAN" for key in categorical_columns})
tab_all = tab_all.fillna({key: -1 for key in real_value_columns})

In [44]:
for k in tab_all.columns:
    print(f"{k} is {len(tab_all[k].unique())}")

id is 36796
org:resource is 2
Activity is 19
time:timestamp is 30141
org:role is 8
case:Rfp_id is 6886
case:Project is 79
case:Task is 597
CaseID is 6886
case:OrganizationalEntity is 36
case:Cost Type is 1
case:RequestedAmount is 6449
case:Activity is 6
case:RfpNumber is 6322

In [45]:
tab_all = tab_all.drop(columns=["case:Rfp_id", "id"])

In [46]:
tab_all.to_csv(data_dir_processed + f"{dataset}_processed_all.csv", index=False)

In [15]:
from math import log


min_time = tab_all['time:timestamp'].min() 

tab_all['time:timestamp'] -= min_time
tab_all['time:timestamp'] = [ log(x)  if x > 0 else 0. for x in tab_all['time:timestamp'].values]


tab_all.head()

,id,org:resource,Activity,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,0.000000,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,3.737670,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,11.499982,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,15.337479,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,15.337486,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [36]:
tab_all["case:RequestedAmount"] = [log(x) if x > 0 else 0. for x in tab_all["case:RequestedAmount"].values]
tab_all.head()

,id,org:resource,Activity,time:timestamp,org:role,case:Rfp_id,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,st_step 148220_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,0.000000,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
1,st_step 148221_0,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,3.737670,SUPERVISOR,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
2,st_step 148222_0,STAFF MEMBER,Request For Payment REJECTED by MISSING,11.499982,MISSING,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
3,st_step 148219_0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,15.337479,EMPLOYEE,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
4,st_step 148218_0,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,15.337486,PRE_APPROVER,request for payment 148214,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215

In [47]:
tab_all

,org:resource,Activity,time:timestamp,org:role,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,0.000000,EMPLOYEE,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
1,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,3.737670,SUPERVISOR,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
2,STAFF MEMBER,Request For Payment REJECTED by MISSING,11.499982,MISSING,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
3,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,15.337479,EMPLOYEE,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
4,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,15.337486,PRE_APPROVER,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
...,...,...,...,...,...,...,...,...,...,...,...,...
36791,STAFF MEMBER,Request For Payment APPROVED by ADMINISTRATION,17.944795,ADMINISTRATION,project 147860,task 152704,request for payment 185000,organizational unit 65468,0,2.734995,activity 505,request for payment number 185001
36792,STAFF MEMBER,Request For Payment APPROVED by BUDGET OWNER,17.951544,BUDGET OWNER,project 147860,task 152704,request for payment 185000,organizational unit 65468,0,2.734995,activity 505,request for payment number 185001
36793,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,17.958401,SUPERVISOR,project 147860,task 152704,request for payment 185000,organizational unit 65468,0,2.734995,activity 505,request for payment number 185001
36794,SYSTEM,Request Payment,17.958428,UNDEFINED,project 147860,task 152704,request for payment 185000,organizational unit 65468,0,2.734995,activity 505,request for payment number 185001
36795,SYSTEM,Payment Handled,17.961625,UNDEFINED,project 147860,task 152704,request for payment 185000,organizational unit 65468,0,2.734995,activity 505,request for payment number 185001

# Split the dataset

In [48]:
split_ratio = 2 / 3

first_act_tab = (
    tab_all.groupby("CaseID").first().sort_values("time:timestamp").reset_index()
)
first_act_tab = first_act_tab[
    ~first_act_tab.duplicated(subset=["CaseID", "Activity"], keep="first")
]
first_act_tab = first_act_tab.reset_index(drop=True)

list_train_valid_cases = list(
    first_act_tab[: int(split_ratio * len(first_act_tab))]["CaseID"].unique()
)

list_train_cases = list_train_valid_cases[: int(len(list_train_valid_cases) * 0.8)]
tab_train = tab_all[tab_all["CaseID"].isin(list_train_cases)].reset_index(drop=True)
tab_train.to_csv(data_dir_processed+ f"{dataset}_processed_train.csv", index = False)

list_valid_cases = list_train_valid_cases[int(len(list_train_valid_cases) * 0.8) :]
tab_valid = tab_all[tab_all["CaseID"].isin(list_valid_cases)].reset_index(drop=True)
tab_valid.to_csv(data_dir_processed+f"{dataset}_processed_valid.csv", index = False)

list_test_cases = list(
    first_act_tab[int(split_ratio * len(first_act_tab)) :]["CaseID"].unique()
)
tab_test = tab_all[tab_all["CaseID"].isin(list_test_cases)].reset_index(drop=True)
tab_test.to_csv(data_dir_processed+ f"{dataset}_processed_test.csv", index = False)

In [ ]:
tab_all.columns

In [49]:
tab_train

,org:resource,Activity,time:timestamp,org:role,case:Project,case:Task,CaseID,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,0.000000,EMPLOYEE,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
1,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,3.737670,SUPERVISOR,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
2,STAFF MEMBER,Request For Payment REJECTED by MISSING,11.499982,MISSING,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
3,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,15.337479,EMPLOYEE,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
4,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,15.337486,PRE_APPROVER,project 148216,UNKNOWN,request for payment 148214,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
...,...,...,...,...,...,...,...,...,...,...,...,...
19054,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,17.660319,EMPLOYEE,project 147908,UNKNOWN,request for payment 166372,organizational unit 65488,0,3.241908,UNKNOWN,request for payment number 166373
19055,STAFF MEMBER,Request For Payment APPROVED by ADMINISTRATION,17.660320,ADMINISTRATION,project 147908,UNKNOWN,request for payment 166372,organizational unit 65488,0,3.241908,UNKNOWN,request for payment number 166373
19056,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,17.672043,SUPERVISOR,project 147908,UNKNOWN,request for payment 166372,organizational unit 65488,0,3.241908,UNKNOWN,request for payment number 166373
19057,SYSTEM,Request Payment,17.682338,UNDEFINED,project 147908,UNKNOWN,request for payment 166372,organizational unit 65488,0,3.241908,UNKNOWN,request for payment number 166373
19058,SYSTEM,Payment Handled,17.688054,UNDEFINED,project 147908,UNKNOWN,request for payment 166372,organizational unit 65488,0,3.241908,UNKNOWN,request for payment number 166373

### Prepare the graphs

In [50]:
from utils import get_case_ids, is_static, get_one_hot_encoder, get_one_hot_encodings

from torch import tensor, max, int64, float32
from torch_geometric.data import HeteroData
import numpy as np

In [51]:
def get_node_features(dataset: pd.DataFrame, trace: pd.DataFrame, cat_features, real_features) -> dict:
    columns_static = [c for c in trace if is_static(trace[c])]

    res = {}

    for key in trace:
        values = trace[key].values
        
        
        if key in cat_features:
            onehot_encoder = get_one_hot_encoder(dataset, key)
            if key not in columns_static:
                res[key] = tensor(
                    get_one_hot_encodings(onehot_encoder, values),
                    dtype=float32,
                    requires_grad=True
                )
            else:
                res[key] = tensor(
                    get_one_hot_encodings(onehot_encoder, np.array([values[0]])),
                    dtype=float32,
                    requires_grad=True
                )
        if key in real_features:
            if key not in columns_static:
                res[key] = tensor(values,  dtype=float32,requires_grad=True)
            else:
                res[key] = tensor([values[0]], dtype=float32,requires_grad=True)
            res[key] = res[key].reshape(res[key].shape[0], 1)
        
    

    return res

In [52]:


def compute_edges_indexs(node_features: dict, prefix_len):
    res = {}
    keys = node_features.keys()
    # indexes = [[i, j] for i in range(prefix_len) for j in range(i + 1, prefix_len)]
    indexes = [[i, i + 1] for i in range(prefix_len-1)]
    # activities indexes
    for k in keys:
        if len(node_features[k]) != 1:
            if k == "Activity":
                res[(k, "followed_by", k)] = indexes
                for k2 in keys:
                    if k2 != k:
                        if len(node_features[k2]) == 1:
                            res[(k, "related_to", k2)] = [
                                [i, 0] for i in range(prefix_len)
                            ]
                        else:
                            res[(k, "related_to", k2)] = [
                                [i, i] for i in range(prefix_len)
                            ]
            else:
                res[(k, "related_to", k)] = indexes

    return res

In [53]:
import torch

from torch import cat

def compute_edges_features(node_features, edges_indexes, cat_features, real_features):
    res = {}

    for k in edges_indexes:
        if k[0] == k[2]:
            indexes = edges_indexes[k]
            res[k] = []
            
            if k[0] in cat_features:
                for i in indexes:
                        res[k].append(      
                            cat(
                                (
                                    tensor([torch.equal(node_features[k[0]][i[0]],node_features[k[0]][i[1]])], dtype=torch.float32),
                                    tensor([i[1] - i[0]], dtype=torch.float32),
                                )
                            )
                        )
            elif k[0] in real_features:
                for i in indexes:
                        res[k].append(
                            tensor(
                                [
                                    node_features[k[0]][i[1]]
                                    - node_features[k[0]][i[0]],
                                    i[1] - i[0],
                                ]
                            )
                        )
            

    return res

In [70]:
# from pprint import pprint as print

from torch import stack

def build_prefixes_graph_from_trace(dataset, trace, cat_features, real_features):
    X = []  # graphs
   

    node_features = get_node_features(dataset, trace, cat_features, real_features)
    
    
    prefix_lenghts = range(2, len(trace))
    # print(prefix_lenghts)
    for prefix in prefix_lenghts:
        # print(prefix)

        # init node types and features
        G = HeteroData()
        for k in node_features:
            G[k].x = node_features[k][:prefix]
        

        edges_indexes = compute_edges_indexs(node_features, prefix)

        edge_features = compute_edges_features(node_features, edges_indexes, cat_features, real_features)
        
        for k in edge_features:
            G[k].edge_attr = stack(edge_features[k])
            


        for k in edges_indexes:
            ce = [[], []]
            for i in range(len(edges_indexes[k])):
                ce[0].append(edges_indexes[k][i][0])
                ce[1].append(edges_indexes[k][i][1])
            edges_indexes[k] = ce

        for k in edges_indexes:
            G[k].edge_index = tensor(edges_indexes[k], dtype=int64)

        G.y = {}
        for k in node_features:
            if k in cat_features:
                G.y[k] = torch.max(node_features[k][0],0)[1] if len(node_features[k]) == 1 else torch.max(node_features[k][prefix], 0)[1]
            else:
                G.y[k] = torch.tensor([node_features[k][prefix][0]]) if len(node_features[k]) > 1 else node_features[k][0].clone().detach()
        
        X.append(G)

        
    return X

## Create the datasets

In [61]:
case_train_ids = get_case_ids(tab_train)
case_valid_ids = get_case_ids(tab_valid)
case_test_ids = get_case_ids(tab_test)

In [62]:
print(len(case_train_ids))
print(len(case_valid_ids))
print(len(case_test_ids))

3672
918
2296

In [83]:
trace = (
        tab_train.query(f"CaseID == '{case_train_ids[0]}'")
        .reset_index()
        .drop(columns="index")
        .drop(columns="CaseID")
    )
trace

,org:resource,Activity,time:timestamp,org:role,case:Project,case:Task,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,0.000000,EMPLOYEE,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
1,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,3.737670,SUPERVISOR,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
2,STAFF MEMBER,Request For Payment REJECTED by MISSING,11.499982,MISSING,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
3,STAFF MEMBER,Request For Payment SUBMITTED by EMPLOYEE,15.337479,EMPLOYEE,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
4,STAFF MEMBER,Request For Payment APPROVED by PRE_APPROVER,15.337486,PRE_APPROVER,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
5,STAFF MEMBER,Request For Payment FINAL_APPROVED by SUPERVISOR,15.391828,SUPERVISOR,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
6,SYSTEM,Request Payment,15.428686,UNDEFINED,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215
7,SYSTEM,Payment Handled,15.561581,UNDEFINED,project 148216,UNKNOWN,organizational unit 65463,0,3.536204,UNKNOWN,request for payment number 148215

In [84]:
graphs = build_prefixes_graph_from_trace(tab_all, trace, categorical_columns, real_value_columns)

In [86]:
graphs[1].y

{'org:resource': tensor(0),
 'Activity': tensor(17),
 'time:timestamp': tensor([15.3375]),
 'org:role': tensor(3),
 'case:Project': tensor(17),
 'case:Task': tensor(0),
 'case:OrganizationalEntity': tensor(8),
 'case:Cost Type': tensor(0),
 'case:RequestedAmount': tensor([3.5362]),
 'case:Activity': tensor(0),
 'case:RfpNumber': tensor(131)}

In [87]:
graphs[1].x_dict

{'org:resource': tensor([[1., 0.],
         [1., 0.],
         [1., 0.]], grad_fn=<SliceBackward0>),
 'Activity': tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
          0.],
         [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
          0.]], grad_fn=<SliceBackward0>),
 'time:timestamp': tensor([[ 0.0000],
         [ 3.7377],
         [11.5000]], grad_fn=<SliceBackward0>),
 'org:role': tensor([[0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0.]], grad_fn=<SliceBackward0>),
 'case:Project': tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0.]], grad_fn=<SliceBackward0>),
 'case:Task': tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0.]], grad_fn=<SliceBackward0>),
 'case:OrganizationalEntity': tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
        grad_fn=<SliceBackward0>),
 'case:Cost Type': tensor([[1.]], grad_fn=<SliceBackward0>),
 'case:RequestedAmount': tensor([[3.5362]], grad_fn=<SliceBackward0>),
 'case:Activity': tensor([[1., 0., 0., 0., 0., 0.]], grad_fn=<SliceBackward0>),
 'case:RfpNumber': tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<SliceBackward0>)}

In [ ]:
graphs[1].edge_items()

In [88]:
from tqdm.notebook import tqdm


print("Preparing training dataset...")

X_train = []


for i in tqdm(range(len(case_train_ids))):
    trace = (
        tab_train.query(f"CaseID == '{case_train_ids[i]}'")
        .reset_index()
        .drop(columns="index")
        .drop(columns="CaseID")
    )
    graphs = build_prefixes_graph_from_trace(dataset=tab_all, trace=trace, cat_features=categorical_columns, real_features=real_value_columns)
    
    # print(trace)
    # print([x.x_dict for x in graphs[:2]])
    # print(labels[:2])
    # break

    for i in range(len(graphs)):
        X_train.append(graphs[i])
        

# Y_train = tensor(Y_train, dtype=float32)

print("Done!\n\n")

Preparing training dataset...

  0%|          | 0/3672 [00:00<?, ?it/s]

Done!

In [89]:
print("Preparing validation dataset...")

X_valid = []


for i in tqdm(range(len(case_valid_ids))):
    trace = (
        tab_valid.query(f"CaseID == '{case_valid_ids[i]}'")
        .reset_index()
        .drop(columns="index")
        .drop(columns="CaseID")
    )
    graphs = build_prefixes_graph_from_trace(dataset=tab_all, trace=trace,cat_features=categorical_columns, real_features=real_value_columns)
    for i in range(len(graphs)):
        X_valid.append(graphs[i])
       

# Y_valid = tensor(Y_valid)

print("Done!\n\n")

Preparing validation dataset...

  0%|          | 0/918 [00:00<?, ?it/s]

Done!

In [90]:
print("Preparing test dataset...")

X_test = []


for i in tqdm(range(len(case_test_ids))):
    trace = (
        tab_test.query(f"CaseID == '{case_test_ids[i]}'")
        .reset_index()
        .drop(columns="index")
        .drop(columns="CaseID")
    )
    graphs = build_prefixes_graph_from_trace(dataset=tab_all, trace=trace,cat_features=categorical_columns, real_features=real_value_columns)
    for i in range(len(graphs)):
        X_test.append(graphs[i])
     

# Y_test = tensor(Y_test)

print("Done!\n\n")

Preparing test dataset...

  0%|          | 0/2296 [00:00<?, ?it/s]

Done!

### Let's Save the graph datasets

In [91]:
import pickle

with open(data_dir_graphs + dataset + "_TRAIN_event_prediction_FINAL.pkl", "wb") as f:
    pickle.dump(X_train, f)
with open(data_dir_graphs + dataset + "_VALID_event_prediction_FINAL.pkl", "wb") as f:
    pickle.dump(X_valid, f)
with open(data_dir_graphs + dataset + "_TEST_event_prediction_FINAL.pkl", "wb") as f:
    pickle.dump(X_test, f)